const kelurahanData = [
    { id: 1, name: "Harapan Baru", kecamatan: "Loa Janan Ilir" },
    { id: 2, name: "Rapak Dalam", kecamatan: "Loa Janan Ilir" },
    { id: 3, name: "Sengkotek", kecamatan: "Loa Janan Ilir" },
    { id: 4, name: "Simpang Tiga", kecamatan: "Loa Janan Ilir" },
    { id: 5, name: "Tani Anam", kecamatan: "Loa Janan Ilir" },
    { id: 6, name: "Batuas", kecamatan: "Palaran" },
    { id: 7, name: "Bukuan", kecamatan: "Palaran" },
    { id: 8, name: "handil", kecamatan: "Palaran" },
    { id: 9, name: "Rawa Makmur", kecamatan: "Palaran" },
    { id: 10, name: "Simpang Pasir", kecamatan: "Palaran" },
    { id: 11, name: "Pelita", kecamatan: "Samarinda Ilir" },
    { id: 12, name: "Selili", kecamatan: "Samarinda Ilir" },
    { id: 13, name: "Sidodamai", kecamatan: "Samarinda Ilir" },
    { id: 14, name: "Sidomulyo", kecamatan: "Samarinda Ilir" },
    { id: 15, name: "Sungai Dama", kecamatan: "Samarinda Ilir" },
    { id: 16, name: "Bugis", kecamatan: "Samarinda Kota" },
    { id: 17, name: "Karang Mumus", kecamatan: "Samarinda Kota" },
    { id: 18, name: "Pasar Pagi", kecamatan: "Samarinda Kota" },
    { id: 19, name: "Pelabuhan", kecamatan: "Samarinda Kota" },
    { id: 20, name: "Sungai Pinang Luar", kecamatan: "Samarinda Kota" },
    { id: 21, name: "Baqa", kecamatan: "Samarinda Seberang" },
    { id: 22, name: "Gunung Panjang", kecamatan: "Samarinda Seberang" },
    { id: 23, name: "Mangkupalas", kecamatan: "Samarinda Seberang" },
    { id: 24, name: "Mesjid", kecamatan: "Samarinda Seberang" },
    { id: 25, name: "Sungai Keledang", kecamatan: "Samarinda Seberang" },
    { id: 26, name: "Tenun", kecamatan: "Samarinda Seberang" },
    { id: 27, name: "Air Hitam", kecamatan: "Samarinda Ulu" },
    { id: 28, name: "Air Putih", kecamatan: "Samarinda Ulu" },
    { id: 29, name: "Bukit Pinang", kecamatan: "Samarinda Ulu" },
    { id: 30, name: "Dadi Mulya", kecamatan: "Samarinda Ulu" },
    { id: 31, name: "Gunung Kelua", kecamatan: "Samarinda Ulu" },
    { id: 32, name: "Jawa", kecamatan: "Samarinda Ulu" },
    { id: 33, name: "Sidodadi", kecamatan: "Samarinda Ulu" },
    { id: 34, name: "Teluk Lerong Ilir", kecamatan: "Samarinda Ulu" },
    { id: 35, name: "Budaya Pampang", kecamatan: "Samarinda Utara" },
    { id: 36, name: "Lempake", kecamatan: "Samarinda Utara" },
    { id: 37, name: "Sempaja Barat", kecamatan: "Samarinda Utara" },
    { id: 38, name: "Sempaja Utara", kecamatan: "Samarinda Utara" },
    { id: 39, name: "Sempaja Selatan", kecamatan: "Samarinda Utara" },
    { id: 40, name: "Sempaja Timur", kecamatan: "Samarinda Utara" },
    { id: 41, name: "Sungai Siring", kecamatan: "Samarinda Utara" },
    { id: 42, name: "Tanah Merah", kecamatan: "Samarinda Utara" },
    { id: 43, name: "Makroman", kecamatan: "Sambutan" },
    { id: 44, name: "Pulau Atas", kecamatan: "Sambutan" },
    { id: 45, name: "Sambutan", kecamatan: "Sambutan" },
    { id: 46, name: "Sindang Sari", kecamatan: "Sambutan" },
    { id: 47, name: "Sungai Kapih", kecamatan: "Sambutan" },
    { id: 48, name: "Loa Buah", kecamatan: "Sungai Kunjang" },
    { id: 49, name: "Loa Bakung", kecamatan: "Sungai Kunjang" },
    { id: 50, name: "Loa Bahu", kecamatan: "Sungai Kunjang" },
    { id: 51, name: "Karang Anyar", kecamatan: "Sungai Kunjang" },
    { id: 52, name: "Karang Asam Ilir", kecamatan: "Sungai Kunjang" },
    { id: 53, name: "Karang Asam Ulu", kecamatan: "Sungai Kunjang" },
    { id: 54, name: "Teluk Lerong Ulu", kecamatan: "Sungai Kunjang" },
    { id: 55, name: "Bandara", kecamatan: "Sungai Pinang" },
    { id: 56, name: "Gunung Lingai", kecamatan: "Sungai Pinang" },
    { id: 57, name: "Mugirejo", kecamatan: "Sungai Pinang" },
    { id: 58, name: "Sungai Pinang Dalam", kecamatan: "Sungai Pinang" },
    { id: 59, name: "Temindung Permai", kecamatan: "Sungai Pinang" },
];

export default kelurahanData;